### ISSUE TITLE
Api Endpoint

### ISSUE THREAD

**Issue by madzae** [ans-4175/random-gofood#15]
Hallo,

Kurang paham soal javascript, tapi berminat bikin peta merchant gofood. Kalau boleh tahu, api endpoint aplikasi ini apa ya? Kalau saya baca di kode, base urlnya "https://random-gofood-api.vercel.app" dengan tambahan "/random" dan parametel berupa koordinat. Kalau langsung tembak misalnya, "https://random-gofood-api.vercel.app/random/-6.65629,10.97897" jadi error.

Terima kasih.

**Comment by ans-4175** [comment]
Hi, seharusnya seperti ini untuk koordinat yang kamu inginkan
```
https://random-gofood-api.vercel.app/random?lat=-6.889779413770388&long=107.66659290930028
```
