### ISSUE TITLE
customize banyaknya list merchant

### ISSUE THREAD

**Issue by k1m0ch1** [ans-4175/random-gofood#7]
kurang banyak aja list merchant nya. makin banyak makin seru.

**Comment by ans-4175** [comment]
tampilannya nanti bagaimana @k1m0ch1 ?
Sebenarnya balikan dari API-nya sudah 60 merchants, tapi aku pilih 10 untuk masuk di wheels (secara random)

**Comment by ans-4175** [comment]
Tampilannya mungkin seperti quiz "picker winner" begitu?

**Comment by ans-4175** [comment]
closed by transferred to issue #10
