### ISSUE TITLE
Customize List Merchant by categories

### ISSUE THREAD

**Issue by k1m0ch1** [ans-4175/random-gofood#8]
AUTHOR
Berdasar dari https://github.com/ans-4175/random-gofood/issues/4#issuecomment-969912345
Issue ini menjadi bagian untuk Part III
Mengakomodir "Merchant List" berdasar kategori

===
ORIGINAL
you know sometimes in the group we want "I want X, I want Y, I want Z" how about we roll X Y Z ?

so it like randomize but the custom merchant, because we don't want to roll the "merchant W"

**Comment by ans-4175** [comment]
Customize apanya ya?
Ga kebayang..

**Comment by ans-4175** [comment]
Kebayang untuk customize/categorize merchantnya biar bisa milih kategori: makanan (berat), minuman, cemilan, kopi(?)
Nyambung dengan API-nya https://github.com/ans-4175/random-gofood-api/issues/3

**Comment by ans-4175** [comment]
Issue ini, sudah dapat list category dari API implemented disini
https://github.com/ans-4175/random-gofood-api/commit/3c0a1b56a3a73aa06a05e70115cebb564d14b5d9
// type = 'FOOD', 'DRINK', 'SNACK', 'COFFEE'
Aku coba buat masuk di bagian ini dengan ui wired-combo

cc @imballinst
